custom:
  - "Support Holy Private Bookmarks development"
  - ""
  - "Cryptocurrency donations:"
  - "Bitcoin (BTC): bc1q9rz9uu9c48ydrmgrmu9kzqjp9mrdzavcll09uq"
  - "Ethereum (ETH): 0xAc862138b1ebF8d7F4fdb23D821489Cf91c314d0"
